SQL DATA ANALYTICS — 75 PRACTICE QUESTIONS
Database: Pagila / PostgreSQL

============================================================
Q1–Q15: BASIC SQL
============================================================

Q1. Find the first name, last name, and email of all active customers.

Q2. Find the first name, last name, and customer ID of the 10 customers with the highest customer IDs.

Q3. Find all films with a rental rate greater than 4.00. Display the title and rental rate, ordered by rental rate descending.

Q4. Find the average rental rate of all films.

Q5. Find the number of films for each rating. Order the results by the number of films descending.

Q6. Find the 5 longest films. Display the title and length.

Q7. Find the total amount of all payments.

Q8. Find the minimum, maximum, and average rental rate of all films.

Q9. Find the number of customers in each store. Order the results by customer count descending.

Q10. Find the average rental rate for each film rating. Order the results by average rental rate descending.

Q11. Find the total payment amount made by each customer. Order by total payment descending.

Q12. Find the number of rentals made by each customer. Order by rental count descending.

Q13. Find the number of rentals handled by each staff member. Order by rental count descending.

Q14. Find customers who have made more than 25 rentals. Display the customer ID and rental count, ordered by rental count descending.

Q15. Find the average payment amount for each customer. Order by average payment descending.


============================================================
Q16–Q25: AGGREGATION / HAVING
============================================================

Q16. Find the total revenue generated by each staff member. Order by total revenue descending.

Q17. Find film ratings that contain more than 200 films. Display the rating and number of films.

Q18. Find the total payment amount for each payment date. Order by total payment descending.

Q19. Find the minimum, maximum, and average payment amount for each staff member. Order by average payment descending.

Q20. Find customers whose total payment is greater than 150. Display customer ID and total payment.

Q21. Find each customer's first name, last name, and number of rentals. Include customers who have no rentals. Order by rental count descending.

Q22. Find each film title and the number of times it has been rented. Order by rental count descending.

Q23. Find each customer's first name, last name, and total payment amount. Include customers with no payments. Order by total payment descending.

Q24. Find each staff member's first name and total payment amount handled. Order by total payment descending.

Q25. Find each film category and the number of films in that category. Include categories with no films. Order by film count descending.


============================================================
Q26–Q40: JOINS
============================================================

Q26. Find each actor's first name, last name, and number of films they appear in. Order by film count descending.

Q27. Find each film title and its category name. Order by category name and then film title.

Q28. Find each customer's first name, last name, and number of payments. Include customers with no payments. Order by payment count descending.

Q29. Find each staff member's first name and number of rentals handled. Include staff with no rentals. Order by rental count descending.

Q30. Find each customer's first name, last name, and number of different films they have rented. Order by the number of different films descending.

Q31. Find each film title and its total revenue generated from rentals. Exclude films that have no revenue. Order by revenue descending.

Q32. Find each customer's first name, last name, and total revenue they generated. Order by total revenue descending.

Q33. Find each film category and its total revenue. Order by total revenue descending.

Q34. Find each actor's first name, last name, and total revenue generated by the films they appear in. Order by revenue descending.

Q35. Find each film category and the number of rentals made for films in that category. Order by rental count descending.

Q36. Find each customer's first name, last name, and number of different film categories they have rented from. Order by category count descending.

Q37. Find each film title and the number of actors appearing in it. Order by actor count descending.

Q38. Find each actor's first name, last name, and number of different film categories they have appeared in. Order by category count descending.

Q39. Find each store and the number of distinct customers associated with that store. Order by customer count descending.

Q40. Find each language and the number of films available in that language. Order by film count descending.


============================================================
Q41–Q50: PRACTICAL SQL — CASE / BUSINESS QUESTIONS
============================================================

Q41. For every film, display its title, rental rate, and classify the rental rate as:
     - Low if below 1.00
     - Medium if between 1.00 and 3.00
     - High if above 3.00
     Order by rental rate descending.

Q42. For every customer, calculate total payment and classify the customer as:
     - Low if total payment is below 50
     - Medium if total payment is between 50 and 100
     - High if total payment is above 100
     Order by total payment descending.

Q43. For every film, display its title, rental duration, and classify the rental duration as:
     - Short if 3 days or less
     - Medium if 4–5 days
     - Long if above 5 days
     Order by rental duration descending.

Q44. For every staff member, calculate total revenue and classify revenue as:
     - Low if below 3000
     - Medium if between 3000 and 3500
     - High if above 3500
     Order by total revenue descending.

Q45. For every film, display its title, length, and classify the film length as:
     - Short if below 90 minutes
     - Medium if 90–120 minutes
     - Long if above 120 minutes
     Order by film length descending.

Q46. For every customer, calculate the number of rentals and classify them as:
     - Low if fewer than 20 rentals
     - Medium if 20–30 rentals
     - High if more than 30 rentals
     Order by rental count descending.

Q47. For each film rating, calculate the average rental rate and classify the average as:
     - Low if below 2.50
     - Medium if between 2.50 and 3.00
     - High if above 3.00
     Order by average rental rate descending.

Q48. For each film category, calculate the number of films and classify the category size as:
     - Small if fewer than 50 films
     - Medium if 50–70 films
     - Large if above 70 films
     Order by film count descending.

Q49. For each store, calculate the number of customers and classify the store as:
     - Small if fewer than 300 customers
     - Medium if 300–305 customers
     - Large if above 305 customers
     Order by customer count descending.

Q50. For every film, display its title, replacement cost, and classify the cost as:
     - Low if below 15
     - Medium if 15–25
     - High if above 25
     Order by replacement cost descending.


============================================================
Q51–Q60: SUBQUERIES
============================================================

Q51. Find customers whose total payment is greater than the average total payment across all customers.

Q52. Find films whose rental rate is greater than every PG-13 film.

Q53. Find customers whose number of rentals is greater than the average number of rentals per customer.

Q54. Find films whose rental rate is greater than the average rental rate for films with the same rating.

Q55. Find customers whose overall total payment is greater than every customer's total payment generated through Store 1.

Q56. Find films whose replacement cost is greater than the average replacement cost of films in the same replacement-cost category.

Q57. Find customers whose total payment is greater than the average total payment across all customers.

Q58. Find individual payments whose amount is greater than that customer's own average payment amount.

Q59. Find films whose rental rate is greater than the overall average rental rate.

Q60. Find customers whose overall total payment is greater than the highest customer's total payment generated through Store 2.


============================================================
Q61–Q65: DATE FUNCTIONS
============================================================

Q61. Find the total payment amount for each month, separated by year.

Q62. Find the total payment amount for each day of the week.

Q63. Find the total payment amount for each year.

Q64. Find the average payment amount for each month within each year.

Q65. Find the number of payments made during each hour of the day.


============================================================
Q66–Q70: CTEs
============================================================

Q66. Find the top 5 customers whose total payment is above the average customer total payment.

Q67. Find the top 10 films whose revenue is above the average film revenue.

Q68. Find the 10 customers whose rental count is above the average rental count.

Q69. Classify every customer as High or Below Average based on their total payment compared with the average customer total payment.

Q70. Find film categories whose total revenue is above the average category revenue.


============================================================
Q71–Q75: REAL MIXED SQL
============================================================

Q71. Find customers whose total payment is greater than the average total payment.

Q72. Find films whose revenue is greater than the average revenue of films in their own rating.

Q73. Find customers whose total spending is higher than every customer who has fewer than 20 rentals.

Q74. Find films whose rental rate is above the average rental rate for their rating AND whose total revenue is greater than 20.

Q75. Find customers who have more rentals than the average customer AND spent more money than the average customer.


============================================================
END OF 75-QUESTION SQL PRACTICE
============================================================
